version: '3'

services:
  django:
    container_name: django
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate  &&
             python manage.py createsuperuserwithpassword --username admin --password admin --email admin@example.com --preserve
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgresql
    image: postgres
    restart: always
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5433:5432
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge