# Generated by Django 4.0.4 on 2022-05-24 18:21

import apps.borrow.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('numeropedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaprestamo', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('fechamaximadevolucion', models.DateField(blank=True, default=apps.borrow.models.get_fechamaximadevolucion)),
                ('fechadevolucion', models.DateField(blank=True, null=True)),
                ('librocodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('usuariocodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
