# Generated by Django 4.0.4 on 2022-05-20 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('numeropedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaprestamo', models.DateField(blank=True, default=datetime.date(2022, 5, 20))),
                ('fechamaximadevolucion', models.DateField(blank=True, default=datetime.date(2022, 6, 4))),
                ('fechadevolucion', models.DateField()),
                ('librocodigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book')),
                ('usuariocodigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
