# Generated by Django 4.0.4 on 2022-05-20 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fechamaximadevolucion',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 5)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fechaprestamo',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 21)),
        ),
    ]
