# Generated by Django 4.0.4 on 2022-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_fechamaximadevolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fechadevolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
