# Generated by Django 4.0.4 on 2022-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('codigousuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('fechanacimiento', models.DateField()),
                ('dni', models.CharField(blank=True, max_length=12, null=True)),
                ('domicilio', models.CharField(max_length=50)),
                ('poblacion', models.CharField(blank=True, max_length=30, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
